export const TYPES = {
    App: Symbol.for('App'),
    HealthService: Symbol.for('HealthService'),
    HealthController: Symbol.for('HealthController'),
    HealthRoutes: Symbol.for('HealthRoutes'),
    HealthMonitorService: Symbol.for('HealthMonitorService'),
    HealthMonitorController: Symbol.for('HealthMonitorController'),
    HealthMonitorRoutes: Symbol.for('HealthMonitorRoutes'),
    Routes: Symbol.for('Routes'),
    PDFService: Symbol.for('PDFService'),
    TemplateService: Symbol.for('TemplateService'),
    PDFController: Symbol.for('PDFController'),
    PDFRoutes: Symbol.for('PDFRoutes'),
    ValidationService: Symbol.for('ValidationService'),
};