export const TYPES = {
    App: Symbol.for('App'),
    HealthService: Symbol.for('HealthService'),
    HealthController: Symbol.for('HealthController'),
    HealthRoutes: Symbol.for('HealthRoutes'),
    Routes: Symbol.for('Routes'),
    PDFService: Symbol.for('PDFService'),
    TemplateService: Symbol.for('TemplateService'),
    PDFController: Symbol.for('PDFController'),
    PDFRoutes: Symbol.for('PDFRoutes'),
    ValidationService: Symbol.for('ValidationService'),
    RetryService: Symbol.for('RetryService'),
    QueueService: Symbol.for('QueueService'),
    QueueController: Symbol.for('QueueController'),
    QueueRoutes: Symbol.for('QueueRoutes'),
    UserRepository: Symbol.for('UserRepository'),
    JwtService: Symbol.for('JwtService'),
    AuthService: Symbol.for('AuthService'),
    PasswordService: Symbol.for('PasswordService'),
    SessionService: Symbol.for('SessionService'),
    AuthController: Symbol.for('AuthController'),
    AuthRoutes: Symbol.for('AuthRoutes')
};