export const TYPES = {
  App: Symbol.for('App'),
  HealthService: Symbol.for('HealthService'),
  HealthController: Symbol.for('HealthController'),
  HealthRoutes: Symbol.for('HealthRoutes'),
  Routes: Symbol.for('Routes'),
  PDFService: Symbol.for('PDFService'),
  TemplateService: Symbol.for('TemplateService'),
  PDFController: Symbol.for('PDFController'),
  PDFRoutes: Symbol.for('PDFRoutes'),
  ValidationService: Symbol.for('ValidationService'),
  RetryService: Symbol.for('RetryService'),
  UserRepository: Symbol.for('UserRepository'),
  AuthService: Symbol.for('AuthService'),
  AuthController: Symbol.for('AuthController'),
  AuthRoutes: Symbol.for('AuthRoutes'),
};